/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EventApp: typeof import('./src/components/Sections/EventApp.vue')['default']
    FifthPage: typeof import('./src/components/Sections/SliderPages/FifthPage.vue')['default']
    FirstPage: typeof import('./src/components/Sections/SliderPages/FirstPage.vue')['default']
    FooterApp: typeof import('./src/components/Footer/FooterApp.vue')['default']
    FourthPage: typeof import('./src/components/Sections/SliderPages/FourthPage.vue')['default']
    HeaderApp: typeof import('./src/components/Header/HeaderApp.vue')['default']
    JobApp: typeof import('./src/components/Sections/JobApp.vue')['default']
    MarketingApp: typeof import('./src/components/Sections/MarketingApp.vue')['default']
    MissionApp: typeof import('./src/components/Sections/MissionApp.vue')['default']
    ReferenceApp: typeof import('./src/components/Sections/ReferenceApp.vue')['default']
    SecondPage: typeof import('./src/components/Sections/SliderPages/SecondPage.vue')['default']
    SliderApp: typeof import('./src/components/Sections/SliderApp.vue')['default']
    ThirdPage: typeof import('./src/components/Sections/SliderPages/ThirdPage.vue')['default']
  }
}
